GOSUB MENU
 
MENU:
OPCION$ = "A"
CLS
LOCATE 2, 30: PRINT "-programs-"
LOCATE 5, 20: PRINT "1- AGENDA"
LOCATE 6, 20: PRINT "2- AUTOCAD"
LOCATE 7, 20: PRINT "3- ACERCA DE..."
LOCATE 8, 20: PRINT "4- WINBAS..."
LOCATE 9, 20: PRINT "5- SALIR"
LOCATE 20, 20: PRINT "PARA ELEGIR PULSE EL NRO. INDICADO..."
DO
    OPCION$ = INKEY$
LOOP WHILE OPCION$ = ""
 
SELECT CASE OPCION$
    CASE "1"
    GOSUB AGENDA
 
    CASE "2"
    GOSUB AUTOCAD
    
    CASE "3"
    GOSUB ACERCA

    CASE "4"
    GOSUB WINBAS
 
    CASE "5"
    GOSUB SALIR

 
    CASE ELSE
    GOSUB ERRORSELECCION
 
END SELECT
 
AGENDA:
CLS

SHELL "AGENDA"


PRINT "PULSE UNA RECLA PARA VOLVER AL MENU..."
DO
LOOP UNTIL INKEY$ <> ""
CLS
GOSUB MENU
 
AUTOCAD:
CLS

SHELL "AUTOCAD"


PRINT "PULSE UNA RECLA PARA VOLVER AL MENU..."
DO
LOOP UNTIL INKEY$ <> ""
CLS

ACERCA:
CLS
LOCATE 6, 20: PRINT "SISTEMA WINBASIC 2.0"
LOCATE 8, 20: PRINT "PRESIONE UNA TECLA PARA IR AL MENU..."
DO
LOOP UNTIL INKEY$ <> ""
CLS
GOSUB MENU

WINBAS:
CLS

SHELL "WINBAS"


PRINT "PULSE UNA RECLA PARA VOLVER AL MENU..."
DO
LOOP UNTIL INKEY$ <> ""


 
ERRORSELECCION:
LOCATE 22, 30: PRINT "OPCION NO VALIDA!!!"
DO
LOOP UNTIL INKEY$ <> ""
CLS
GOSUB MENU
 
SALIR:
CLS
PRINT "VA A SALIR DEL SISTEMA WINBASIC!!!"
END

