GOSUB MENU
 
MENU:
OPCION$ = "A"
CLS
LOCATE 2, 30: PRINT "-WINBASIC 1.0-"
LOCATE 5, 20: PRINT "1- FILEMAN "
LOCATE 6, 20: PRINT "2- LEAME"
LOCATE 7, 20: PRINT "3- ACERCA DE..."
LOCATE 8, 20: PRINT "4- SALIR"
LOCATE 20, 20: PRINT "PARA ELEGIR PULSE EL NRO. INDICADO..."
DO
    OPCION$ = INKEY$
LOOP WHILE OPCION$ = ""
 
SELECT CASE OPCION$
    CASE "1"
    GOSUB FILEMAN
 
    CASE "2"
    GOSUB LEAME
    
    CASE "3"
    GOSUB ACERCA
 
    
    CASE "4"
    GOSUB SALIR
 
    CASE ELSE
    GOSUB ERRORSELECCION
 
END SELECT
 
FILEMAN:
CLS

SHELL "FILEMAN"


PRINT "PULSE UNA TECLA PARA VOLVER AL MENU..."
DO
LOOP UNTIL INKEY$ <> ""
CLS
GOSUB MENU
 
LEAME:
CLS

SHELL "LEAME"


PRINT "PULSE UNA TECLA PARA VOLVER AL MENU..."
DO
LOOP UNTIL INKEY$ <> ""
CLS

ACERCA:
CLS
LOCATE 6, 20: PRINT "SISTEMA WINBASIC 1.0"
LOCATE 8, 20: PRINT "PRESIONE UNA TECLA PARA IR AL MENU..."
DO
LOOP UNTIL INKEY$ <> ""
CLS
GOSUB MENU
 
ERRORSELECCION:
LOCATE 22, 30: PRINT "OPCION NO VALIDA!!!"
DO
LOOP UNTIL INKEY$ <> ""
CLS
GOSUB MENU
 
SALIR:
CLS
PRINT "VA A SALIR DEL SISTEMA WINBASIC!!!"
END

